name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x
      - run: make fmt-check
        if: matrix.os == 'ubuntu-latest'
      - run: make lint
        if: matrix.os == 'ubuntu-latest'
      - run: |
          make test
          make test-esbuild-deno-loader
